Repository mtvs-server-second-study/developer-agency, pull requests merged in 2023-06, with the labels that each got.

#6 비밀번호 재입력 유효성 검증 기능 구현
  src/main/java/com/onemorething/layered/menu/domain/service/LoginImplService.java
  src/main/java/com/onemorething/layered/menu/infra/service/LoginImplService.java
  src/test/java/com/onemorething/layered/menu/domain/service/LoginImplServiceTest.java
Labels: 😁Feature

#8 회원가입 핸드폰번호 관련 로직 구현
  src/main/java/com/onemorething/layered/menu/domain/service/LoginImplService.java
  src/test/java/com/onemorething/layered/menu/domain/service/LoginImplServicetests.java
Labels: 😁Feature

#10 #2 비밀번호 유효성 검증 기능 구현
  build.gradle
  src/main/java/com/onemorething/layered/menu/domain/service/LoginImplService.java
  src/test/java/com/onemorething/layered/configuration/domain/SignUpValidPwdTests.java
Labels: 😁Feature

#13 ID 유효성 검증 기능 구현 #1
  src/main/java/com/onemorething/layered/menu/application/controller/LoginController.java
  src/main/java/com/onemorething/layered/menu/application/dto/MemberDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/domain/repository/LoginRepository.java
  src/main/java/com/onemorething/layered/menu/domain/service/LoginImplService.java
  src/main/java/com/onemorething/layered/menu/domain/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/infra/repository/LoginImplRepository.java
  src/test/java/com/onemorething/layered/menu/domain/service/LoginImplServiceTest.java
Labels: 😁Feature

#20 메인페이지 매핑, 회원가입 페이지 작성, 회원가입 페이지 입력값 넘기기 #18
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/dto/MemberDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/UserSignUpService.java
Labels: 😁Feature

#22 #17 로그인 session 구현 및 accountController 매핑
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/resources/templates/account/login.html
  src/main/resources/templates/account/signup.html
Labels: 😁Feature

#23 #19 메인페이지와 상세페이지 연결
  src/main/java/com/onemorething/layered/menu/application/controller/ContentsController.java
  src/main/java/com/onemorething/layered/menu/application/service/ContentsService.java
  src/main/resources/templates/contents/detail.html
  src/main/resources/templates/main.html
Labels: 😁Feature

#28 #26 아이디/패스워드 찾기 페이지 구현
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/resources/templates/account/findid.html
  src/main/resources/templates/account/findidresult.html
  src/main/resources/templates/account/findpassword.html
  src/main/resources/templates/account/findpasswordresult.html
  src/main/resources/templates/account/login.html
Labels: 😁Feature

#32 글쓰기 기능 뷰, 컨트롤러, 서비스까지 연결 #30
  src/main/java/com/onemorething/layered/menu/application/controller/ContentsController.java
  src/main/java/com/onemorething/layered/menu/application/dto/WritingDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/WritingService.java
  src/main/resources/templates/contents/writing.html
Labels: 😁Feature

#33 #25 회원가입 유효성 검증,로그인 구조개선
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/dto/MemberDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/UserSignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/login/LoginApiService.java
  src/main/java/com/onemorething/layered/menu/domain/service/login/UserSignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/tokenlogin/LoginApiService.java
  src/main/java/com/onemorething/layered/menu/domain/service/tokenlogin/StackApiService.java
  src/main/java/com/onemorething/layered/menu/infra/service/login/GithubLoginApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/login/GoogleLoginApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/login/KakaoLoginApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/tokenlogin/GithubLoginApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/tokenlogin/GoogleLoginApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/tokenlogin/KakaoLoginApi.java
  src/main/resources/templates/account/signup.html
  src/test/java/com/onemorething/layered/menu/domain/service/SignUpVaildPhoneTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/SignUpValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/SignUpValidPwdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpCheckPwdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpVaildPhoneTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpValidPwdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/tokenlogin/LoginApiServiceTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/tokenlogin/StackApiServiceTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/login/GithubLoginApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/login/GoogleLoginApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/login/KakaoLoginApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/tokenlogin/GithubLoginApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/tokenlogin/GoogleLoginApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/tokenlogin/KakaoLoginApiTests.java
Labels: ⭐️Refactor

#35 feat: mybatis/mySQL 연동 성공, 값 넘어오는 지 확인 완료. 공식문서 보고 resultMap 추가
  build.gradle
  src/main/java/com/onemorething/layered/configuration/MyBatisConfiguration.java
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/dto/UserDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/Member.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/User.java
  src/main/java/com/onemorething/layered/menu/domain/repository/UserRepository.java
  src/main/java/com/onemorething/layered/menu/infra/repository/UserImplRepository.java
  src/main/resources/application.properties
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/account/signup.html
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpValidIdTests.java
Labels: 😁Feature, ⭐️Refactor

#37 #36 로그인 아이디 비밀번호 domain/service 로직 구현
  src/main/java/com/onemorething/layered/menu/domain/service/login/UserLogInService.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/LoginValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/LoginValidPwdTests.java
Labels: 😁Feature

#39 #34 회원가입 로직 DB연동(INSERT) 마무리
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/dto/UserDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/User.java
  src/main/java/com/onemorething/layered/menu/domain/repository/UserRepository.java
  src/main/java/com/onemorething/layered/menu/domain/service/login/UserSignUpService.java
  src/main/java/com/onemorething/layered/menu/infra/repository/LoginImplRepository.java
  src/main/java/com/onemorething/layered/menu/infra/repository/UserImplRepository.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/account/signup.html
  src/main/resources/templates/account/signupresult.html
Labels: 😁Feature

#42 #29 로그인 db 연동
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/controller/MainController.java
  src/main/java/com/onemorething/layered/menu/application/dto/UserDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/User.java
  src/main/java/com/onemorething/layered/menu/domain/repository/UserRepository.java
  src/main/java/com/onemorething/layered/menu/infra/repository/UserImplRepository.java
  src/main/resources/mapper/UserMapper.xml
Labels: 😁Feature

#43 Feature/find id db
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/controller/ContentsController.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/User.java
  src/main/java/com/onemorething/layered/menu/domain/repository/UserRepository.java
  src/main/java/com/onemorething/layered/menu/domain/service/login/UserSignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/tokenlogin/LoginApiService.java
  src/main/java/com/onemorething/layered/menu/infra/repository/UserImplRepository.java
  src/main/resources/application.properties
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/account/signup.html
Labels: 😁Feature

#44 html 양식 적용#27
  src/main/java/com/onemorething/layered/menu/application/service/DetailService.java
  src/main/resources/templates/contents/detail.html
Labels: 😁Feature

#41 #40 패키지 전체 구조 변경
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/login/UserSignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/valid/ValidService.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/LoginValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/LoginValidPwdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpVaildPhoneTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpValidPwdTests.java
Labels: ⭐️Refactor

#47 test: 테스트 코드 기능 별 병합
  src/test/java/com/onemorething/layered/menu/domain/service/login/LoginTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/LoginValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpCheckPwdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpVaildPhoneTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/SignUpValidPwdTests.java
Labels: ⭐️Refactor

#49 로그아웃 기능 구현 #48
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/resources/templates/main.html
Labels: 😁Feature

#52 entity mapperclass 구현 후 SWAP 대체 ,이름 유효성검증 구현
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/dto/UserDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/application/service/UserMapper.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/User.java
  src/main/java/com/onemorething/layered/menu/domain/service/common/ValidService.java
  src/main/java/com/onemorething/layered/menu/domain/service/login/UserSignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/service/signup/SignUpValidService.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/common/LoginValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/common/LoginValidPwdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/common/SignUpValidIdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/common/SignUpValidPwdTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/signup/SignUpCheckPwd.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/signup/SignUpVaildPhoneTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/login/signup/SignUpValidNameTests.java
Labels: 😁Feature, ⭐️Refactor

#51 #29 로그인 구현 완료
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/application/service/UserMapper.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/account/login.html
Labels: 😁Feature

#56 #53 user html 프론트 구현
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/domain/repository/UserRepository.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/static/css/user.css
  src/main/resources/templates/account/findid.html
  src/main/resources/templates/account/findidresult.html
  src/main/resources/templates/account/findpassword.html
  src/main/resources/templates/account/findpasswordresult.html
  src/main/resources/templates/account/login.html
Labels: 😁Feature

#57 #54 회원가입/아이디중복조회
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/User.java
  src/main/java/com/onemorething/layered/menu/domain/exception/test.java
  src/main/java/com/onemorething/layered/menu/domain/repository/UserRepository.java
  src/main/java/com/onemorething/layered/menu/domain/service/tokenlogin/LoginApiService.java
  src/main/java/com/onemorething/layered/menu/domain/service/tokenlogin/StackApiService.java
  src/main/java/com/onemorething/layered/menu/infra/repository/UserImplRepository.java
  src/main/java/com/onemorething/layered/menu/infra/service/stack/GithubChartApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/tokenlogin/GithubLoginApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/tokenlogin/GoogleLoginApi.java
  src/main/java/com/onemorething/layered/menu/infra/service/tokenlogin/KakaoLoginApi.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/account/signup.html
  src/main/resources/templates/account/signupresult.html
Labels: 😁Feature

#59 feat: db 변경에 따른 패키지 구조 변경과 기술스택 db 등록 구현
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/controller/MainController.java
  src/main/java/com/onemorething/layered/menu/application/dto/UserDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/application/service/mapper/SkillMapper.java
  src/main/java/com/onemorething/layered/menu/application/service/mapper/UserMapper.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/Skill.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/SkillAndTech.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/Tech.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/TechStack.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/enumtype/Proficiency.java
  src/main/java/com/onemorething/layered/menu/domain/repository/SkillRepository.java
  src/main/java/com/onemorething/layered/menu/domain/service/signup/SignUpValidService.java
  src/main/java/com/onemorething/layered/menu/infra/repository/SkillImplRepository.java
  src/main/resources/application.properties
  src/main/resources/mapper/SkillMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/account/signup.html
Labels: 😁Feature

#60 #53 html 프론트 구현
  src/main/resources/templates/account/findid.html
  src/main/resources/templates/account/findidresult.html
  src/main/resources/templates/account/findpassword.html
  src/main/resources/templates/account/findpasswordresult.html
  src/main/resources/templates/account/login.html
  src/main/resources/templates/account/signup.html
  src/main/resources/templates/account/signupresult.html
Labels: ⭐️Refactor

#65 #64 사용자편의성 향상
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/account/signup.html
Labels: 🕷️BugFix, ⭐️Refactor

#69 refactor: 불필요 테스트 파일 및 주석 제거
  src/main/java/com/onemorething/layered/menu/application/controller/AccountController.java
  src/main/java/com/onemorething/layered/menu/application/controller/BoardController.java
  src/main/java/com/onemorething/layered/menu/application/service/BoardService.java
  src/main/java/com/onemorething/layered/menu/application/service/LoginService.java
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/java/com/onemorething/layered/menu/application/service/mapper/SkillMapper.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/Board.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/Skill.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/SkillAndTech.java
  src/main/java/com/onemorething/layered/menu/domain/aggregate/entity/Tech.java
  src/main/java/com/onemorething/layered/menu/domain/repository/BoardRepository.java
  src/main/java/com/onemorething/layered/menu/domain/repository/SkillRepository.java
  src/main/java/com/onemorething/layered/menu/domain/repository/TechRepository.java
  src/main/java/com/onemorething/layered/menu/domain/repository/UserRepository.java
  src/main/java/com/onemorething/layered/menu/domain/service/signup/SignUpValidService.java
  src/main/java/com/onemorething/layered/menu/infra/repository/BoardImplRepository.java
  src/main/java/com/onemorething/layered/menu/infra/repository/UserImplRepository.java
  src/main/resources/application.properties
  src/main/resources/mapper/BoardMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/static/css/user.css
  src/main/resources/templates/account/login.html
  src/main/resources/templates/account/signup.html
  src/main/resources/templates/contents/board.html
  src/main/resources/templates/main.html
  src/test/java/com/onemorething/layered/menu/application/dto/MemberDTOTests.java
  src/test/java/com/onemorething/layered/menu/domain/aggregate/entity/MemberTests.java
  src/test/java/com/onemorething/layered/menu/domain/aggregate/entity/TechStackTests.java
  src/test/java/com/onemorething/layered/menu/domain/aggregate/enumtype/OrderableStatusTests.java
  src/test/java/com/onemorething/layered/menu/domain/aggregate/vo/testss.java
  src/test/java/com/onemorething/layered/menu/domain/exception/tests.java
  src/test/java/com/onemorething/layered/menu/domain/repository/UserRepositoryTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/tokenlogin/LoginApiServiceTests.java
  src/test/java/com/onemorething/layered/menu/domain/service/tokenlogin/StackApiServiceTests.java
  src/test/java/com/onemorething/layered/menu/infra/repository/LoginImplRepositoryTests.java
  src/test/java/com/onemorething/layered/menu/infra/repository/UserImplRepositoryTestsTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/stack/GithubChartApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/tokenlogin/GithubLoginApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/tokenlogin/GoogleLoginApiTests.java
  src/test/java/com/onemorething/layered/menu/infra/service/tokenlogin/KakaoLoginApiTests.java
Labels: ⭐️Refactor

#72 #53 html 프론트 구현
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/static/css/user.css
  src/main/resources/templates/account/findid.html
  src/main/resources/templates/account/findpassword.html
  src/main/resources/templates/account/login.html
  src/main/resources/templates/account/signup.html
Labels: 😁Feature

#75 #53 html 프론트 구현
  src/main/java/com/onemorething/layered/menu/application/service/SignUpService.java
  src/main/resources/static/css/user.css
  src/main/resources/templates/account/signup.html
Labels: ⭐️Refactor

#71 feat: 글쓰기 페이지 입력 값의 존재 여부 확인 로직 구현하기 #70
  src/main/java/com/onemorething/layered/menu/application/dto/BoardDTO.java
  src/main/java/com/onemorething/layered/menu/application/service/BoardService.java
  src/main/java/com/onemorething/layered/menu/domain/service/common/ValidService.java
  src/main/resources/mapper/BoardMapper.xml
  src/main/resources/templates/contents/board.html
  src/main/resources/templates/contents/result.html
  src/test/java/com/onemorething/layered/menu/domain/service/common/ValidServiceTest.java
Labels: 😁Feature

#78 병합 누락 파일 재병합 #77
  src/main/java/com/onemorething/layered/menu/application/controller/ContentsController.java
  src/main/resources/static/css/board.css
  src/main/resources/static/js/board.js
  src/main/resources/templates/contents/board.html
  src/main/resources/templates/main.html
Labels: 🕷️BugFix

#81 #80 README.md 수정반영
  README.md
  src/main/java/com/onemorething/layered/menu/domain/aggregate/vo/test.java
Labels: 📋Docs
